# Generated by Django 2.2 on 2019-04-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_confirmed',
        ),
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.IntegerField(default=0),
        ),
    ]
